<a href="https://colab.research.google.com/github/carolsc/I2A2-Challenges/blob/main/Desafio_1_Similaridade_entre_textos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Medida de Similaridade entre textos através da função Containment



---


A Função Containment em Python compará dois textos e analisa a similaridade dos mesmos com relação aos seu n-gramas de interseção.

*N-grama*: É uma sequência de n elementos dentro de uma frase, sejam elas palavras, letras, símbolos, classificação gramatical, entre outros.

Primeiramente temos que contar as ocorrência de n-gramas dos nossos textos. Para isso, iremos usar a função CountVectorizer para converter o conjunto de dados do texto em uma matriz de contagem. Após a criação dessa matriz, iremos analisá-la

In [1]:
# Importação das bibliotecas
import numpy as np
import sklearn

In [31]:
#Importação dos textos
arquivo1 = open ("/content/Base Text - Matrix Representation I - v2.txt", "r")
texto1 = arquivo1.read()
arquivo2 = open ("/content/Base Text - Matrix Representation II - v2.txt", "r")
texto2 = arquivo2.read()


## Unigrama

A execução do exemplo imprime o vocabulário. Os vetores terão o número de palavras no vocabulário.

In [32]:
from sklearn.feature_extraction.text import CountVectorizer

#texto1 = "Donec posuere nec magna eget vulputate."
#texto2 = "Aenean vulputate odio sit amet posuere. "

#Número de n_gramas - palavras
n = 1

#Instância contador de n-gramas
counts = CountVectorizer(analyzer = 'word', ngram_range=(n,n))

#Cria uma matriz de contagem de n-gramas para os dois textos
n_grams = counts.fit_transform({texto1, texto2})

#Cria um dicionário de n-gramas
vocab2int = counts.fit([texto1, texto2]).vocabulary_

n_grams_array = n_grams.toarray()

#Imprime o dicionário de palavras com seu index
print("Vetor de n-gramas: \n", n_grams_array)
print()
print("Dicionários de n-gramas (unigrama): \n", vocab2int)

Vetor de n-gramas: 
 [[2 1 4 ... 1 1 1]
 [0 0 0 ... 0 0 0]]

Dicionários de n-gramas (unigrama): 
 {'de': 354, 'motu': 893, 'circulari': 210, 'fluidorum': 591, 'hypothesis': 660, 'resistentiam': 1275, 'quæ': 1221, 'oritur': 1004, 'ex': 528, 'defectu': 364, 'lubricitatis': 816, 'partium': 1023, 'fluidi': 586, 'cæteris': 339, 'paribus': 1014, 'proportionalem': 1148, 'esse': 510, 'velocitati': 1575, 'qua': 1170, 'partes': 1018, 'separantur': 1343, 'ab': 4, 'invicem': 740, 'prop': 1134, 'li': 790, 'theor': 1493, 'xxxviii': 1641, 'si': 1361, 'cylindrus': 337, 'solidus': 1396, 'infinitè': 708, 'longus': 811, 'in': 694, 'fluido': 590, 'uniformi': 1543, 'infinito': 705, 'circa': 207, 'axem': 156, 'positione': 1104, 'datum': 351, 'cum': 325, 'revolvatur': 1298, 'hujus': 653, 'impulsu': 693, 'solo': 1400, 'agatur': 59, 'fluidum': 592, 'orbem': 998, 'perseveret': 1073, 'autem': 153, 'pars': 1015, 'unaquæque': 1540, 'uniformiter': 1545, 'suo': 1440, 'dico': 413, 'quod': 1215, 'tempora': 1477, 'per

Cada número do vetor representa uma palavra. A linha superior está os n-gramas do texto 1 e na linha inferior do texto 2. Podemos analisar se os texto possuem n_gramas em comum através de suas colunas.

## Valores de containment

O Containment é uma medida de similaridade entre textos. Bsicamente ele realiza a normalização da interseção da contagem de n-gramas entre os textos.

Cálculo de Containment:

1. calcular a interseção n-grama entre o texto 1 e o texto 2.
2. Adiocioanr o número de termos comuns.
3. Normalizar o valor na etapa 2 pelo número de n-gramas no texto1 (ou seja, dividimos o valor pelo total de n-gramas do texto1 (subíndice A))

Equação do Containment:

 ∑ count (ngramA) ⋂ ∑ count(ngramB) / ∑count (ngramA)




In [33]:
n_grams

<2x1652 sparse matrix of type '<class 'numpy.int64'>'
	with 1737 stored elements in Compressed Sparse Row format>

In [34]:
arrays = n_grams.toarray()
arrays

array([[2, 1, 4, ..., 1, 1, 1],
       [0, 0, 0, ..., 0, 0, 0]])

In [35]:
#Cálculo da interseção
#Pega o mínimo valor entre os dois arrays - 0 nçao tem interseção e 1 tem interseção
intersection_list = np.amin(arrays, axis = 0)
intersection_list

array([0, 0, 0, ..., 0, 0, 0])

In [36]:
#Quantidade de palavras similares entre os dois textos
intersection_count = np.sum(intersection_list)
intersection_count

335

In [37]:
#Para Normalização
index_A = 0
A_count = np.sum(arrays[index_A])
A_count

3057

In [38]:
#Grau de similaridade entre os dois textos em porcentagem
(intersection_count/A_count)*100

10.958456002616945